name: testing publish

on:
  workflow_run:
    workflows: ["testing"]
    branches: [dev]
    types:
      - completed

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: helloworld
        shell: bash
        run: |
          echo "hello world"